language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra
    - extra-android-support
    - extra-android-m2repository

licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"

before_script:
    - chmod +x gradlew

script: ./gradlew :krop:assemble
